import argparse
import subprocess
import os
import sys
import shutil

def run_command_with_output(command_list, cwd=None):
    """Utility to run shell commands and capture their output."""
    try:
        result = subprocess.run(command_list, check=True, cwd=cwd, capture_output=True, text=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e.stderr}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Master Workflow: Automated Feed Builder.")
    parser.add_argument("--url", required=True, help="The RSS feed URL")
    parser.add_argument("--lang", help="Optional: Override language detection (e.g., 'fr', 'es')")
    # Added optional --feedname parameter
    parser.add_argument("--feedname", help="Optional: Override discovered feedname")
    args = parser.parse_args()

    podcasts_repo_path = os.path.abspath("Podcasts")

    # 1. Run the processing script and pass the optional language override
    print(f"--- Generating Feed Dashboard for {args.url} ---")
    gen_cmd = ["python3", "show_general_feed.py", "--url", args.url]
    if args.lang:
        gen_cmd.extend(["--lang", args.lang])
        
    stdout_output = run_command_with_output(gen_cmd)

    # 2. Extract feedname and lang from the script output
    # If --feedname is provided, we use it. Otherwise, we detect it.
    feedname = args.feedname if args.feedname else None
    lang = args.lang if args.lang else "unknown"
    
    for line in stdout_output.splitlines():
        if not feedname and line.startswith("FEEDNAME_OUTPUT:"):
            feedname = line.replace("FEEDNAME_OUTPUT:", "").strip()
        if not args.lang and line.startswith("LANG_OUTPUT:"):
            lang = line.replace("LANG_OUTPUT:", "").strip()

    if not feedname:
        print("[!] Error: show_general_feed.py failed to return a feedname and no override was provided.")
        sys.exit(1)

    print(f"--- Using Feedname: {feedname} (Language: {lang}) ---")

    # 3. Define and move the generated files
    # If feedname was overridden, we need to find the file generated by the sub-script first
    # show_general_feed.py always generates a file based on its own slugify logic.
    original_feedname = None
    for line in stdout_output.splitlines():
        if line.startswith("FEEDNAME_OUTPUT:"):
            original_feedname = line.replace("FEEDNAME_OUTPUT:", "").strip()

    # The file created by show_general_feed.py
    source_feed_file = f"{original_feedname}.feed.html"
    # The name we want it to have in the Podcasts repo
    target_feed_file = f"{feedname}.feed.html"

    if not os.path.exists(podcasts_repo_path):
        print(f"[!] Error: Podcasts directory not found at {podcasts_repo_path}")
        sys.exit(1)

    if os.path.exists(source_feed_file):
        print(f"--- Moving {source_feed_file} to {podcasts_repo_path} as {target_feed_file} ---")
        dest = os.path.join(podcasts_repo_path, target_feed_file)
        if os.path.exists(dest):
            os.remove(dest)
        shutil.move(source_feed_file, dest)
    else:
        print(f"[!] Warning: {source_feed_file} was not generated.")
        sys.exit(1)

    # 4. Git Operations
    print(f"--- Staging and Pushing to Repository ---")
    commit_message = f"Update feed: {feedname} ({lang})"
    
    try:
        # Use the target_feed_file name for git operations
        subprocess.run(["git", "add", target_feed_file], cwd=podcasts_repo_path, check=True)
        subprocess.run(["git", "commit", "-m", commit_message], cwd=podcasts_repo_path, check=True)
        subprocess.run(["git", "push"], cwd=podcasts_repo_path, check=True)
        print(f"--- Workflow Complete! {feedname} dashboard is live. ---")
    except subprocess.CalledProcessError:
        print("Nothing to commit (or git error), skipping push.")

if __name__ == "__main__":
    main()
    
