import argparse
import subprocess
import os
import sys
import shutil
import feedparser
import re

def slugify(text):
    """Converts a string into a short, filename-friendly slug."""
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')[:15]

def run_command_with_output(command_list, cwd=None):
    """Utility to run shell commands and capture their output."""
    try:
        result = subprocess.run(command_list, check=True, cwd=cwd, capture_output=True, text=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e.stderr}")
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Master Workflow: Automated Feed Builder.")
    parser.add_argument("--url", required=True, help="The RSS feed URL")
    parser.add_argument("--lang", help="Optional: Override language detection (e.g., 'fr', 'es')")
    parser.add_argument("--feedname", help="Optional: Override discovered feedname")
    args = parser.parse_args()

    podcasts_repo_path = os.path.abspath("Podcasts")

    # 1. Determine Feedname (Passed in or Discovered)
    feedname = args.feedname
    if not feedname:
        print(f"--- Discovering feedname for {args.url} ---")
        feed = feedparser.parse(args.url)
        title = feed.feed.get('title', 'Unknown Podcast')
        feedname = slugify(title)
        print(f"--- Determined Feedname: {feedname} ---")

    # 2. Run show_general_feed.py passing the determined feedname
    print(f"--- Generating Feed Dashboard for {feedname} ---")
    gen_cmd = ["python3", "show_general_feed.py", "--url", args.url, "--feedname", feedname]
    if args.lang:
        gen_cmd.extend(["--lang", args.lang])
        
    stdout_output = run_command_with_output(gen_cmd)

    # 3. Extract final language (if it was auto-detected by the sub-script)
    lang = args.lang if args.lang else "unknown"
    for line in stdout_output.splitlines():
        if not args.lang and line.startswith("LANG_OUTPUT:"):
            lang = line.replace("LANG_OUTPUT:", "").strip()

    # 4. Move the generated file
    # Since we passed --feedname, the source and target names are now identical
    feed_file = f"{feedname}.feed.html"

    if not os.path.exists(podcasts_repo_path):
        print(f"[!] Error: Podcasts directory not found at {podcasts_repo_path}")
        sys.exit(1)

    if os.path.exists(feed_file):
        print(f"--- Moving {feed_file} to {podcasts_repo_path} ---")
        dest = os.path.join(podcasts_repo_path, feed_file)
        if os.path.exists(dest):
            os.remove(dest)
        shutil.move(feed_file, dest)
    else:
        print(f"[!] Error: {feed_file} was not generated by show_general_feed.py.")
        sys.exit(1)

    # 5. Git Operations
    print(f"--- Staging and Pushing to Repository ---")
    commit_message = f"Update feed: {feedname} ({lang})"
    
    try:
        subprocess.run(["git", "add", feed_file], cwd=podcasts_repo_path, check=True)
        subprocess.run(["git", "commit", "-m", commit_message], cwd=podcasts_repo_path, check=True)
        subprocess.run(["git", "push"], cwd=podcasts_repo_path, check=True)
        print(f"--- Workflow Complete! {feedname} dashboard is live. ---")
    except subprocess.CalledProcessError:
        print("Nothing to commit (or git error), skipping push.")

if __name__ == "__main__":
    main()
    
