import argparse
import requests
import whisper
import json
import warnings
import os
from deep_translator import GoogleTranslator

# Suppress the urllib3/LibreSSL warning
warnings.filterwarnings("ignore", message=".*urllib3 v2 only supports OpenSSL 1.1.1+.*")

def process_podcast(url, feedname, date):
    # Dynamically name all files for persistence
    audio_file = f"{feedname}.{date}.mp3"
    json_output = f"transcript.{feedname}.{date}.json"
    html_output = f"{feedname}.{date}.html"
    
    # 1. Download
    print(f"Downloading audio to: {audio_file}")
    r = requests.get(url, stream=True)
    if r.status_code == 200:
        with open(audio_file, 'wb') as f:
            for chunk in r.iter_content(8192):
                f.write(chunk)
    else:
        print(f"Failed to download audio. Status code: {r.status_code}")
        return

    # 2. Transcribe with Whisper
    print(f"Transcribing with Whisper (Output: {json_output})...")
    model = whisper.load_model("base")
    result = model.transcribe(audio_file, language='sv')
    
    # 3. Process segments for Highlighting
    print("Translating segments and attaching timestamps...")
    translator = GoogleTranslator(source='sv', target='en')
    segments = result.get('segments', [])
    web_data = []
    
    for seg in segments:
        sv_text = seg['text'].strip()
        if sv_text:
            web_data.append({
                "start": round(seg['start'], 2),
                "end": round(seg['end'], 2),
                "sv": sv_text,
                "en": translator.translate(sv_text)
            })

    # 4. Save JSON
    with open(json_output, 'w', encoding='utf-8') as f:
        json.dump(web_data, f, ensure_ascii=False, indent=2)
    
    # 5. Create the Functional HTML Player
    html_template = f"""
    <!DOCTYPE html>
    <html lang="sv">
    <head>
        <meta charset="UTF-8">
        <title>{feedname} - {date}</title>
        <style>
            body {{ font-family: sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px; background: #f4f4f9; }}
            .player-container {{ position: sticky; top: 0; background: white; padding: 20px; border-bottom: 2px solid #ccc; z-index: 100; }}
            audio {{ width: 100%; }}
            .transcript {{ display: flex; flex-direction: column; gap: 10px; margin-top: 20px; }}
            .row {{ display: flex; gap: 20px; padding: 10px; border-radius: 5px; transition: 0.3s; cursor: pointer; }}
            .row:hover {{ background: #eee; }}
            .row.highlight {{ background: #fff9c4; border-left: 5px solid #fbc02d; font-weight: bold; }}
            .sv {{ flex: 1; font-size: 1.1em; color: #1a237e; }}
            .en {{ flex: 1; font-size: 1.1em; color: #455a64; font-style: italic; }}
        </style>
    </head>
    <body>
        <div class="player-container">
            <h1>{feedname.upper()} | {date}</h1>
            <audio id="audio" controls src="{audio_file}"></audio>
        </div>
        <div id="transcript" class="transcript"></div>

        <script>
            const audio = document.getElementById('audio');
            const transcriptDiv = document.getElementById('transcript');
            let data = [];

            // Load the specific JSON file generated by the script
            fetch('{json_output}')
                .then(response => response.json())
                .then(json => {{
                    data = json;
                    data.forEach((item, index) => {{
                        const row = document.createElement('div');
                        row.className = 'row';
                        row.id = 'row-' + index;
                        row.innerHTML = `<div class="sv">${{item.sv}}</div><div class="en">${{item.en}}</div>`;
                        row.onclick = () => audio.currentTime = item.start;
                        transcriptDiv.appendChild(row);
                    }});
                }});

            audio.addEventListener('timeupdate', () => {{
                const time = audio.currentTime;
                data.forEach((item, index) => {{
                    const el = document.getElementById('row-' + index);
                    if (time >= item.start && time <= item.end) {{
                        el.classList.add('highlight');
                        // Auto-scroll logic
                        if (!el.dataset.scrolled) {{
                            el.scrollIntoView({{ behavior: 'smooth', block: 'center' }});
                            el.dataset.scrolled = "true";
                        }}
                    }} else {{
                        el.classList.remove('highlight');
                        delete el.dataset.scrolled;
                    }}
                }});
            }});
        </script>
    </body>
    </html>
    """
    
    with open(html_output, 'w', encoding='utf-8') as f:
        f.write(html_template)
    
    print(f"\nSuccess! Created {json_output}, {audio_file}, and {html_output}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", required=True)
    parser.add_argument("--feedname", required=True)
    parser.add_argument("--date", required=True)
    args = parser.parse_args()
    process_podcast(args.url, args.feedname, args.date)

